cameras = {
    "Common": [
        "Canon",
        "Nikon"
    ],
    "Medium": [
        "Sony",
        "Pentax",
        "Olympus"
    ],
    "Rare": [
        "Hasselblad",
        "Leica",
        "Konica",
        "Zenza Bronica",
        "Rollei",
        "Mamiya",
        "Fujifilm",
        "iPhone",
        "Phase One",
        "Sinar",
        "Smena",
        "P30 Pro",
        "Keksipurkki"
    ]
}

tips = [
    "Laita kohde varjoon",
    "Reeniä reeniä",
    "Vaihda canoniin",
    "Vaihda nikoniin",
    "Vaihda sonyyn",
    "Vaihda smenaan",
    "Rembrandtit kuntoon",
    "Hommaa savukone",
    "Horisontti suoraan",
    "Nosta tummaa alapäätä",
    "Aina voi vetää mustavalkoseks",
    "Osta kalliimpi kamera",
    "vitsisauna.preset",
    "Puolipilvinen on paras kuvauskeli. Ei muutaku F22 ja iso400 sekä haarukointi -2/3. Ei voi epäonnistua ja jos epäonnistuu niin tiputa f22->f11",
    "'No ei se väline siinä oo se oleellinen. Mul on ykköset sit muista syistä.'\n-Petri Mast 2018",
    "Kuvaisit filmiä",
    "Jos ei oo mallia niin aina voi kuvata omia jalkoja",
    "Yhtäkään raajaa ei leikata!",
    "Clarity aina 100",
    "Kultainen leikkaus tai mene roskiin",
    "1.4 ei himmennetä koskaan",
    "1.4 voi joskus himmentää",
    "Älä käytä sigmaa oikeissa kuvauksissa",
    "Älä käytä f22, kun kuvaat makroja. Difraktio on vittumainen suure",
    "Parhaat kuvat sisältää aina vähän syntiä ;)",
    "Muistakaa käyttää P(rofessional)-modee",
    "Kovalevytila on halpaa ja pilvipalvelut rajattomia <3",
    "Valovoima on ylivoimaa",
    "Laskeudu koiran tasolle",
    "Pidä kädessäsi lelua tai ruokaa ja heiluttele sitä linssin ympärillä",
    "Kärsivällisyyttä",
    "Vaimoni on Sääksmäeltä.\n -markku",
    "Muuta Sastamalaan",
    "Älä osta presettejä!",
    "Sammuta kamera kun irroitat vakaajallista putkea",
    "Jos filmillä epäonnistuu, niin voi kattoo vaan peiliin ja nähdä mistä se epäonnistuminen johtuu",
    "Manuaalilla ku tarkentaa niin aina osuu",
    "Kyllä sillä roskalavalta noukitulla keksipurkillakin saa kunnon kuvaa osaavissa käsissä",
    "Joistakin malleista ei millään saa elävän tuntuisia kuvia. Tällöin yksi cocktail auttaa hyvän tuloksen saamiseksi paremmin kuin yhden voimakkaan lampun antama lisävalo.",
    "Mitä vaikeempi asento sen taiteellisempi kuva!",
    "Gammasäteily ei häikäise",
    "Paras kamera ei ole kaikille sama",
    "Osta sääkin oma Smenas, ne ei paljon maksa",
    "Tarkista kaikkien kameroiden kellot ennen ku alat vetää",
    "Kuivaa jalusta huolella jos uitat sen kokonaan järvessä",
    "Treenaa pohkeita",
    "Miten vauvan saa niin vakavaks, että rembrant toimii? \n-Laitat pehmolelut silppuriin",
    "Mene mukaan tilanteisiin hienovaraisesti",
    "Smenalla: Aukko f/11 tai 16, tarkennus mieluummin ylä- kun alakanttiin",
    "Isolla aukolla vain jos on pakko",
    "Ainoo mitä tiedän synnytyksestä on että ilokaasunaamari tippuu helposti pöhnässä naamalta. Kannattaa nojata naamalla seinään silleen että ilokaasunaamari pysyy suulla.",
    "Mustavalkokuvassa ei näy huulipuna",
    "Jos kuvasi tulee päätymään Aamulehteen (Moro) niin varmista, että kuvaat vaakakuvia",
    "Servo päälle ja nappi pohjaan ja kotona sitten katotaan kuvat",
    "Skannaa mieluusti negat muualla ko keittiössä, staattinen sähkö vetään puoleensa leivänmuruja",
    "Smena on täydellinen",
    "Kameroita ei voi olla ikinä liikaa",
    "3D-mallinnus on kuvankäsittelytyökalu"
    "Passikuvan voi ottaa vaikka puhelimella kotona 😅 siin ei oo kovat vaatimukset",
    "Julkaiskaa enemmän, saa palautetta ja myöhemmin saa myötistellä eiku siis näkee kuinka on kehittyny kuvaajana"
]

stickers = [
    "CAADAgADHgEAAiHfMQE_pcz3yBGAdwI",
    "CAADAgADHwEAAiHfMQEXT1Wc5kaV8gI",
    "CAADAgADIAEAAiHfMQHFbatSWwQ6mwI",
    "CAADAgADIQEAAiHfMQEwSd7-kQ3ZzwI",
    "CAADAgADIgEAAiHfMQHWUdn8W0SWIgI",
    "CAADAgADIwEAAiHfMQHomsn1D7HKgwI",
    "CAADAgADJAEAAiHfMQE_3L8FUCy5mAI",
    "CAADAgADJQEAAiHfMQHoa0eq8gMQQgI",
    "CAADAgADJgEAAiHfMQFfuet8AQonfQI",
    "CAADAgADJwEAAiHfMQFbUFb_ZvhP3wI",
    "CAADAgADKQEAAiHfMQEzSzvBQXK6ZAI",
    "CAADAgADKgEAAiHfMQHFRCZkdTPsPgI",
    "CAADAgADKwEAAiHfMQFErv4OBIMsmgI",
    "CAADAgADLAEAAiHfMQFH0kcHTH4kLwI",
    "CAADAgADLQEAAiHfMQEjqKVrImVu-QI",
    "CAADAgADLwEAAiHfMQFW2k6yC7S89gI",
    "CAADAgADMAEAAiHfMQHOeD8t4RpKdQI",
    "CAADAgADMQEAAiHfMQEV_vOfugxzWQI",
    "CAADAgADMgEAAiHfMQGvwJ0R7hkY1wI",
    "CAADAgADMwEAAiHfMQGo7x3k4zYV2AI",
    "CAADAgADNQEAAiHfMQEXYrv_e-bTTQI",
    "CAADAgADNgEAAiHfMQG61gVJBdYGsgI",
    "CAADAgADNwEAAiHfMQFCOmLZRIWT6wI",
    "CAADAgADOAEAAiHfMQHrVlMzh_6spAI",
    "CAADAgADOQEAAiHfMQERN2AYOZOWSAI",
    "CAADAgADOgEAAiHfMQGu8kHMV8j2yQI",
    "CAADAgADOwEAAiHfMQEGEuo2aOVjJQI",
    "CAADAgADPAEAAiHfMQFoe7pULYz-dgI",
    "CAADAgADPQEAAiHfMQHQWA2hUjh8vAI",
    "CAADAgADPgEAAiHfMQEBK8_HYkAw-AI",
    "CAADAgADPwEAAiHfMQHrlpGey2GaBAI",
    "CAADAgADQQEAAiHfMQFYXPeFrSBPuwI"
]
